### ISSUE TITLE
Could not get it running on Windows 8.1 nor Ubuntu

### ISSUE THREAD

**Issue by ViliusKraujutis** [makerspacelt/NTAduino#1]
Is it still possible to run it on Windows 8.1? Tried to install [USBASP](http://www.fischl.de/usbasp/) drivers by [disabling Windows' driver signature enforcement](https://openchrysalis.wordpress.com/2014/09/26/installing-usbasp-driver-software-in-windows-8-1/).

Error pops up like this:
![popup](https://cloud.githubusercontent.com/assets/1859636/13652429/d0238654-e654-11e5-9327-5ebccc8f0dfb.png)
Then information dialog:
![dialog](https://cloud.githubusercontent.com/assets/1859636/13652505/2f16e908-e655-11e5-8cdb-dd930e2e83d3.png)

Any ideas?

**Comment by dariuskasiulevicius** [comment]
Yes, you can make work on latest Windows OS version. What a coincidence yesterday we run USBASP on Windows 10, even more we have compiled example and uploaded to original NTAduino board using latest Arduino IDE.

**Comment by ViliusKraujutis** [comment]
@Matrooskin, could you please share link to USBASP? Maybe I've used incorrect version or so?

**Comment by dariuskasiulevicius** [comment]
I think you are using same as we do from page [fischl.de](http://www.fischl.de/usbasp/usbasp-windriver.2011-05-28.zip). We are used "libusb_1.2.4.0" folder. As shown on wizard [page](https://openchrysalis.files.wordpress.com/2014/09/usbasp-driver-install-step-5.jpg) you need select correct path to drivers.
We restarted windows and after that connected NTAduino board to PC. After connecting to USB port you need press and hold programming button on NTAduino board until you install drivers.

**Comment by ViliusKraujutis** [comment]
Aha! So pressing and holding programming button did the trick. Also I updated Windows 8.1 to Windows 10.

Now I see `USBasp` device in my devices list:
![USBasp](https://cloud.githubusercontent.com/assets/1859636/13728235/f9fd33ea-e919-11e5-9096-801d12089985.png)

Although in `Arduino 1.6.8` IDE, menu `Tools`->`Ports` is grayed out. Hence I can't run any code on NTAduino yet. Do I need to prepare Arduino IDE more?

**Comment by dariuskasiulevicius** [comment]
In that case you need update Arduino IDE configuration file. Go to {ARDUINO}/hardware/arduino/boards.txt where '{ARDUINO}' represents the directory into which the Arduino IDE and supporting files have been installed.
You need add this lines and restart IDE:
##############################################################
NTAduino.name=NTAduino

NTAduino.upload.tool=avrdude
NTAduino.upload.protocol=usbasp
NTAduino.upload.maximum_size=6388
NTAduino.upload.speed=19200

NTAduino.build.mcu=atmega8
NTAduino.build.f_cpu=16000000L
NTAduino.build.core=arduino
NTAduino.build.variant=standard

NTAduino.upload.disable_flushing=true
##############################################################

After restarting IDE you will see NTAduino on board choice. Plus you need select Programmer: "USBasp". When you want send program to board you need press and hold programming button until all data transfer to NTAduino.

**Comment by dariuskasiulevicius** [comment]
On any Arduino IDE version you need choose only Board and Proggrammer. You don't need select port, because you are using USB, and USBasp must find port by self.

**Comment by ViliusKraujutis** [comment]
Thanks, I managed to update code in NTAduino now. All works on my machine now. I used Arduino 1.6.0, as 1.6.8 could not recognize newly added NTAduino board.

Also, I noticed, that it's required **_to hold reset button since plugging board to the computer until all code is uploaded to the baord**_. 
Otherwise I would get this error:

> avrdude: Warning: cannot query manufacturer for device: libusb0-dll:err [control_msg] sending control message failed, win error: A device attached to the system is not functioning.
> 
> avrdude: Warning: cannot query product for device: libusb0-dll:err [control_msg] sending control message failed, win error: A device attached to the system is not functioning.
> 
> avrdude: error: could not find USB device with vid=0x16c0 pid=0x5dc vendor='www.fischl.de' product='USBasp'
